### ISSUE TITLE
Promotion Warhead Crash

### ISSUE THREAD

**Issue by ABrandau** [AttacqueSuperior/Engine#57]
I do not know how I did this, happened when using a FireArmament PromotionWarhead setup on some units.

```OpenRA engine version {DEV_VERSION}
Shattered Paradise mod version {Build 20180521}
on map 6810662e22092aec4877424a4a86ae410ccb3cc8 (Las Palmas by V ( Trempler )).
Date: 2018-05-24 02:18:39Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.ArgumentException`: Revoking experience is not implemented.
Parameter name: amount
   at OpenRA.Mods.Common.Traits.GainsExperience.GiveExperience(Int32 amount, Boolean silent) in c:\Users\Alfredo\Desktop\SP 20180509\OpenRA.Mods.Common\Traits\GainsExperience.cs:line 89
   at OpenRA.Mods.Common.Traits.GainsExperience.GiveLevels(Int32 numLevels, Boolean silent) in c:\Users\Alfredo\Desktop\SP 20180509\OpenRA.Mods.Common\Traits\GainsExperience.cs:line 83
   at OpenRA.Mods.AS.Warheads.PromotionWarhead.DoImpact(Target target, Actor firedBy, IEnumerable`1 damageModifiers)
   at OpenRA.GameRules.WeaponInfo.Impact(Target target, Actor firedBy, IEnumerable`1 damageModifiers) in C:\Users\Alfredo\Desktop\SP 20180510 I\OpenRA.Game\GameRules\WeaponInfo.cs:line 188
   at OpenRA.Mods.Common.Projectiles.InstantHit.Tick(World world) in c:\Users\Alfredo\Desktop\SP 20180509\OpenRA.Mods.Common\Projectiles\InstantHit.cs:line 76
   at OpenRA.World.<Tick>b__91_1(IEffect e) in C:\Users\Alfredo\Desktop\SP 20180510 I\OpenRA.Game\World.cs:line 355
   at OpenRA.WorldUtils.DoTimed[T](IEnumerable`1 e, Action`1 a, String text) in C:\Users\Alfredo\Desktop\SP 20180510 I\OpenRA.Game\WorldUtils.cs:line 75
   at OpenRA.World.Tick() in C:\Users\Alfredo\Desktop\SP 20180510 I\OpenRA.Game\World.cs:line 355
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in C:\Users\Alfredo\Desktop\SP 20180510 I\OpenRA.Game\Game.cs:line 605
   at OpenRA.Game.LogicTick() in C:\Users\Alfredo\Desktop\SP 20180510 I\OpenRA.Game\Game.cs:line 629
   at OpenRA.Game.Loop() in C:\Users\Alfredo\Desktop\SP 20180510 I\OpenRA.Game\Game.cs:line 759
   at OpenRA.Game.Run() in C:\Users\Alfredo\Desktop\SP 20180510 I\OpenRA.Game\Game.cs:line 799
   at OpenRA.Game.InitializeAndRun(String[] args) in C:\Users\Alfredo\Desktop\SP 20180510 I\OpenRA.Game\Game.cs:line 253
   at OpenRA.Program.Main(String[] args) in C:\Users\Alfredo\Desktop\SP 20180510 I\OpenRA.Game\Support\Program.cs:line 37
```

**Comment by GraionDilach** [comment]
You sure this wasn't acused by a typo with the PromotionWarhead having negative GiveLevels?

**Comment by ABrandau** [comment]
Cant say, afaik this setup has been tested in games, and there havent been any reports of this crash yet.
